package GUI;

public class menuAdm extends javax.swing.JFrame {

    public menuAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoPerfil = new javax.swing.JButton();
        botaoProjetos = new javax.swing.JButton();
        botaoCadastrarCliente = new javax.swing.JButton();
        botaoCadastrarProjeto = new javax.swing.JButton();
        botaoMensagens = new javax.swing.JButton();
        botaoAdmSuporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Administrador");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 451));

        botaoPerfil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoPerfil.setForeground(new java.awt.Color(255, 153, 51));
        botaoPerfil.setText("Perfil");
        botaoPerfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(203, 203, 203), 1, true));
        botaoPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoPerfil.setFocusPainted(false);
        botaoPerfil.setFocusable(false);
        botaoPerfil.setMaximumSize(new java.awt.Dimension(81, 17));
        botaoPerfil.setMinimumSize(new java.awt.Dimension(81, 17));
        botaoPerfil.setPreferredSize(new java.awt.Dimension(72, 26));
        botaoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPerfilActionPerformed(evt);
            }
        });

        botaoProjetos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoProjetos.setForeground(new java.awt.Color(255, 153, 51));
        botaoProjetos.setText("Projetos");
        botaoProjetos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(203, 203, 203), 1, true));
        botaoProjetos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoProjetos.setFocusPainted(false);
        botaoProjetos.setFocusable(false);
        botaoProjetos.setMaximumSize(new java.awt.Dimension(81, 17));
        botaoProjetos.setMinimumSize(new java.awt.Dimension(81, 17));
        botaoProjetos.setPreferredSize(new java.awt.Dimension(81, 17));
        botaoProjetos.setRequestFocusEnabled(false);
        botaoProjetos.setRolloverEnabled(false);
        botaoProjetos.setVerifyInputWhenFocusTarget(false);
        botaoProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProjetosActionPerformed(evt);
            }
        });

        botaoCadastrarCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoCadastrarCliente.setForeground(new java.awt.Color(255, 153, 51));
        botaoCadastrarCliente.setText("Cadastrar Cliente");
        botaoCadastrarCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(203, 203, 203), 1, true));
        botaoCadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoCadastrarCliente.setFocusPainted(false);
        botaoCadastrarCliente.setFocusable(false);
        botaoCadastrarCliente.setMaximumSize(new java.awt.Dimension(81, 17));
        botaoCadastrarCliente.setMinimumSize(new java.awt.Dimension(81, 17));
        botaoCadastrarCliente.setPreferredSize(new java.awt.Dimension(81, 17));
        botaoCadastrarCliente.setRequestFocusEnabled(false);
        botaoCadastrarCliente.setRolloverEnabled(false);
        botaoCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarClienteActionPerformed(evt);
            }
        });

        botaoCadastrarProjeto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoCadastrarProjeto.setForeground(new java.awt.Color(255, 153, 51));
        botaoCadastrarProjeto.setText("Cadastrar Projeto");
        botaoCadastrarProjeto.setActionCommand("Cadastro de Projeto");
        botaoCadastrarProjeto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(203, 203, 203), 1, true));
        botaoCadastrarProjeto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoCadastrarProjeto.setFocusPainted(false);
        botaoCadastrarProjeto.setFocusable(false);
        botaoCadastrarProjeto.setRequestFocusEnabled(false);
        botaoCadastrarProjeto.setRolloverEnabled(false);
        botaoCadastrarProjeto.setVerifyInputWhenFocusTarget(false);
        botaoCadastrarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarProjetoActionPerformed(evt);
            }
        });

        botaoMensagens.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoMensagens.setForeground(new java.awt.Color(255, 153, 51));
        botaoMensagens.setText("Mensagens");
        botaoMensagens.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(203, 203, 203), 1, true));
        botaoMensagens.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoMensagens.setFocusPainted(false);
        botaoMensagens.setRequestFocusEnabled(false);
        botaoMensagens.setRolloverEnabled(false);
        botaoMensagens.setVerifyInputWhenFocusTarget(false);
        botaoMensagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMensagensActionPerformed(evt);
            }
        });

        botaoAdmSuporte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoAdmSuporte.setForeground(new java.awt.Color(255, 153, 51));
        botaoAdmSuporte.setText("Cadastro Administrador/Suporte");
        botaoAdmSuporte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(203, 203, 203), 1, true));
        botaoAdmSuporte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botaoAdmSuporte.setFocusPainted(false);
        botaoAdmSuporte.setFocusable(false);
        botaoAdmSuporte.setMargin(new java.awt.Insets(2, 5, 2, 5));
        botaoAdmSuporte.setMaximumSize(new java.awt.Dimension(81, 17));
        botaoAdmSuporte.setMinimumSize(new java.awt.Dimension(81, 17));
        botaoAdmSuporte.setPreferredSize(new java.awt.Dimension(81, 17));
        botaoAdmSuporte.setRequestFocusEnabled(false);
        botaoAdmSuporte.setRolloverEnabled(false);
        botaoAdmSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdmSuporteActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoEsticada.png"))); // NOI18N

        jButton1.setText("Teste");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoMensagens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoCadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoCadastrarProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoAdmSuporte, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAdmSuporte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastrarProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPerfilActionPerformed
        
        perfilUsuario perfil = new perfilUsuario();
        perfil.setVisible(true);
        dispose();

    }//GEN-LAST:event_botaoPerfilActionPerformed

    private void botaoProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProjetosActionPerformed
        
        telaProjetos projeto = new telaProjetos();
        projeto.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_botaoProjetosActionPerformed

    private void botaoCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarClienteActionPerformed
        
        telaCadastroCliente cliente = new telaCadastroCliente();
        cliente.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_botaoCadastrarClienteActionPerformed

    private void botaoAdmSuporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdmSuporteActionPerformed
       
        telaCadastroAdministrador adm = new telaCadastroAdministrador();
        adm.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_botaoAdmSuporteActionPerformed

    private void botaoCadastrarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarProjetoActionPerformed
        
        telaCadastroProjeto cadastro = new telaCadastroProjeto();
        cadastro.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_botaoCadastrarProjetoActionPerformed

    private void botaoMensagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMensagensActionPerformed
       
        telaMensagemCliente mensagem = new telaMensagemCliente();
        mensagem.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_botaoMensagensActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        telaDeUsuarios tela = new telaDeUsuarios();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdmSuporte;
    private javax.swing.JButton botaoCadastrarCliente;
    private javax.swing.JButton botaoCadastrarProjeto;
    private javax.swing.JButton botaoMensagens;
    private javax.swing.JButton botaoPerfil;
    private javax.swing.JButton botaoProjetos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
