/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.*;
import modelo.*;

import java.sql.Connection;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gomes
 */
public class telaCadastroProjeto extends javax.swing.JFrame {
    
    private final Connection connection;

    CadastroDAO daoCadastro = login.getDaoCadastro();
    ProjetoDAO daoProjeto = login.getDaoProjeto();
    UsuarioDAO daoUsuario = login.getDaoUsuario();
    
    Projeto projeto = login.getProjeto();
    Mensagem mensagem = login.getMensagem();
    Usuario usuario= login.getUsuario();
    
    /**
     * Creates new form telaProjetos
     */
    public telaCadastroProjeto() {
        initComponents();
        this.connection = new factory.ConnectionFactory().getConnection();
        
         setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNomeProjeto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoNomeEmpresa = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoCadastrarProjeto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(549, 297));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Projeto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 549, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Nome do projeto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        campoNomeProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNomeProjeto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 51)));
        campoNomeProjeto.setMinimumSize(new java.awt.Dimension(64, 30));
        campoNomeProjeto.setPreferredSize(new java.awt.Dimension(64, 30));
        campoNomeProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeProjetoActionPerformed(evt);
            }
        });
        jPanel1.add(campoNomeProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 280, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Nome da empresa");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        campoNomeEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoNomeEmpresa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 31)));
        campoNomeEmpresa.setMinimumSize(new java.awt.Dimension(64, 30));
        campoNomeEmpresa.setPreferredSize(new java.awt.Dimension(64, 30));
        campoNomeEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeEmpresaActionPerformed(evt);
            }
        });
        jPanel1.add(campoNomeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 280, -1));

        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoVoltar.setForeground(new java.awt.Color(255, 153, 51));
        botaoVoltar.setText("Voltar");
        botaoVoltar.setPreferredSize(new java.awt.Dimension(100, 30));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        botaoLimpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoLimpar.setForeground(new java.awt.Color(255, 153, 51));
        botaoLimpar.setText("Limpar");
        botaoLimpar.setPreferredSize(new java.awt.Dimension(100, 30));
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        jPanel1.add(botaoLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        botaoCadastrarProjeto.setBackground(new java.awt.Color(255, 153, 51));
        botaoCadastrarProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoCadastrarProjeto.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrarProjeto.setText("Cadastrar");
        botaoCadastrarProjeto.setPreferredSize(new java.awt.Dimension(100, 30));
        botaoCadastrarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarProjetoActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCadastrarProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarProjetoActionPerformed
       
        if(campoNomeProjeto.getText().isEmpty() || campoNomeEmpresa.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Favor preencher todos os campos");
            return;
        }
        
        if(daoProjeto.existeProjeto(campoNomeProjeto.getText())){
            JOptionPane.showMessageDialog(null, "Esse projeto já existe");
            return;
        }
        
        projeto.setNomeProjeto(campoNomeProjeto.getText());
        projeto.setEmpresaProjeto(campoNomeEmpresa.getText());
        
        daoProjeto.adicionaProjeto(projeto);
        JOptionPane.showMessageDialog(null, "Enviado com sucesso!");
        campoNomeProjeto.setText("");
        campoNomeEmpresa.setText("");
        
        
      
    }//GEN-LAST:event_botaoCadastrarProjetoActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        
        menuAdm adm = new menuAdm();
        adm.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void campoNomeEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeEmpresaActionPerformed

    private void campoNomeProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeProjetoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastroProjeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrarProjeto;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField campoNomeEmpresa;
    private javax.swing.JTextField campoNomeProjeto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
